title: MinSeok's blog
subtitle: "a.k.a Carne"
email: kms74568@gmail.com
description: "실무를 통한 경험이나 학습에서 배운 지식들을 저장하고 공유하기 위한 블로그입니다."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kangmsc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KangMSC

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
locale: "ko-KR"

repository: "KangMSC/KangMSC.github.io"
logo: "/assets/images/88x88.png"
breadcrumbs: true
date_format: "%Y-%m-%d"
enable_copy_code_button: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"

search: true
search_provider: algolia
algolia:
  application_id: 9W5YH4ZBR4
  index_name: Index
  search_only_api_key: 70e7f825189717a08b57ea2378fa2920
  powered_by: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: true
      related: true