# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MinSeok's blog
subtitle: "a.k.a Carne"
email: kms74568@gmail.com
description: "실무를 통한 경험이나 학습에서 배운 지식들을 저장하고 공유하기 위한 블로그입니다."
repository: "KangMSC/KangMSC.github.io"
logo: "/assets/images/88x88.png"
breadcrumbs: true
date_format: "%Y-%m-%d"
enable_copy_code_button: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kangmsc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KangMSC

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
locale: "ko-KR"

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: true
      related: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
