title: MinSeok's blog
subtitle: "a.k.a Carne"
email: kms74568@gmail.com
description: "실무를 통한 경험이나 학습에서 배운 지식들을 저장하고 공유하기 위한 블로그입니다."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kangmsc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KangMSC

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
locale: "ko-KR"

repository: "KangMSC/KangMSC.github.io"
logo: "/assets/images/88x88.png"
breadcrumbs: true
date_format: "%Y-%m-%d"
enable_copy_code_button: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"

search: true
search_provider: algolia
algolia:
  application_id: 9W5YH4ZBR4
  index_name: Index
  search_only_api_key: 70e7f825189717a08b57ea2378fa2920
  powered_by: true

google_site_verification: "miXqjMyUgmXDRP62KH27D3dYZ4Px7TH0OK67Hjapbns"
naver_site_verification: "2182463b2694afe676c80431e593f1c0468dae09"
bing_site_verification: "AFB8EAEECA6C43A35EA0DD1443371070"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KangMSC"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: true
      related: true
#      classes: wide
      toc: true
      toc_label: "목차"
      toc_icon: "list"